# Generated by Django 3.2 on 2023-07-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semestre_actual',
            field=models.IntegerField(null=True),
        ),
    ]
