# Generated by Django 4.1 on 2023-07-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="semestre_actual",
            field=models.IntegerField(null=True),
        ),
    ]
