# Generated by Django 5.1.2 on 2025-08-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_completado',
            field=models.BooleanField(default=False, help_text='Indica si el alumno ya proporcionó su email'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_requerido',
            field=models.EmailField(blank=True, help_text='Email institucional del alumno', max_length=254, null=True),
        ),
    ]
