# Generated by Django 4.1 on 2023-07-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Alumnos', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_cuenta',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
