# Generated by Django 5.1.2 on 2024-11-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_alter_inscripcion_unique_together_inscripcion_grupo_and_more'),
        ('users', '0002_alter_user_options_alter_user_numero_cuenta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AddField(
            model_name='user',
            name='grupos',
            field=models.ManyToManyField(related_name='alumnos', through='inscripcion.Inscripcion', to='inscripcion.grupo'),
        ),
    ]
