# Generated by Django 5.1.2 on 2025-08-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_completado_user_email_requerido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_requerido',
            field=models.EmailField(blank=True, help_text='Email del alumno', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_cuenta',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
