# Generated by Django 5.1.2 on 2025-08-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_requerido_alter_user_numero_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='numero_cuenta',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
