# Generated by Django 5.1.2 on 2024-11-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_grupos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Alumnos', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='grupos',
        ),
    ]
