# Generated by Django 4.1 on 2023-07-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "clave_asignatura",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("denominacion", models.CharField(max_length=80)),
                ("semestre", models.PositiveIntegerField()),
                ("creditos", models.PositiveIntegerField(default=None)),
            ],
        ),
    ]
