# Generated by Django 5.1.2 on 2024-11-05 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('clave_asignatura', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=80)),
                ('caracter', models.PositiveSmallIntegerField(choices=[(1, 'Obligatoria'), (2, 'Optativa')], default=1)),
                ('semestre', models.PositiveSmallIntegerField(choices=[(0, 'Optativa'), (1, 'Primer Semestre'), (2, 'Segundo Semestre'), (3, 'Tercer Semestre'), (4, 'Cuarto Semestre'), (5, 'Quinto Semestre'), (6, 'Sexto Semestre'), (7, 'Séptimo Semestre'), (8, 'Octavo Semestre')], default=1)),
                ('creditos', models.PositiveSmallIntegerField(default=0)),
                ('eje', models.PositiveSmallIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'M'), (4, 'T')], default=1)),
            ],
            options={
                'ordering': ['semestre', 'clave_asignatura'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('clave_grupo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre'), (3, 'Tercer Semestre'), (4, 'Cuarto Semestre'), (5, 'Quinto Semestre'), (6, 'Sexto Semestre'), (7, 'Séptimo Semestre'), (8, 'Octavo Semestre'), (9, 'Noveno Semestre')])),
                ('asignaturas', models.ManyToManyField(related_name='asignaturas', to='inscripcion.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asignatura', models.ManyToManyField(to='inscripcion.asignatura')),
                ('numero_cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.periodo')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('numero_cuenta', 'periodo')},
            },
        ),
    ]
