# Generated by Django 3.2.8 on 2023-06-29 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('numero_cuenta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre o nombres', max_length=50)),
                ('apellido_paterno', models.CharField(help_text='Apellido Paterno', max_length=50)),
                ('apellido_materno', models.CharField(help_text='Apellido Materno', max_length=50)),
                ('edad', models.IntegerField(help_text='Edad')),
                ('fecha_ingreso', models.DateField()),
                ('semestre_actual', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1)),
                ('foto', models.ImageField(upload_to='fotos_alumnos/')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('clave_asignatura', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=80)),
                ('semestre', models.CharField(max_length=50)),
                ('alumnos', models.ManyToManyField(to='inscripcion.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.asignatura')),
                ('numero_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('clave_grupo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('asignaturas', models.ManyToManyField(to='inscripcion.Asignatura')),
            ],
        ),
    ]
