# Generated by Django 5.1.2 on 2024-11-11 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='asignaturas',
        ),
        migrations.AddField(
            model_name='grupo',
            name='alumnos',
            field=models.ManyToManyField(related_name='alumnos', to=settings.AUTH_USER_MODEL),
        ),
    ]
