# Generated by Django 3.2 on 2023-07-08 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='creditos',
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='semestre',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ManyToManyField(to='inscripcion.Asignatura')),
                ('numero_cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('clave_grupo', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('asignaturas', models.ManyToManyField(related_name='asignaturas', to='inscripcion.Asignatura')),
            ],
        ),
    ]
