# Generated by Django 5.1.2 on 2024-12-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='comprobante_descargado',
            field=models.BooleanField(default=False),
        ),
    ]
