# Generated by Django 5.1.2 on 2024-12-04 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_inscripcion_comprobante_descargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='comprobante_descargado',
        ),
    ]
