# Generated by Django 3.2.8 on 2023-07-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_auto_20230629_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos_alumnos/'),
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='asignatura',
            field=models.ManyToManyField(to='inscripcion.Asignatura'),
        ),
    ]
