# Generated by Django 4.1 on 2023-07-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['semestre', 'clave_asignatura']},
        ),
    ]
