# Generated by Django 4.1 on 2023-07-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
