# Generated by Django 3.2.8 on 2023-07-01 01:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_auto_20230630_1919'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='inscripcion',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
