# Generated by Django 5.1.2 on 2024-11-12 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_remove_grupo_alumnos_grupo_asignaturas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('numero_cuenta', 'periodo', 'grupo')},
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='inscripcion.grupo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupo',
            name='asignaturas',
            field=models.ManyToManyField(related_name='grupos', to='inscripcion.asignatura'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='numero_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='asignatura',
        ),
    ]
