# Generated by Django 4.1 on 2023-07-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_alter_asignatura_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
