# Generated by Django 5.1.2 on 2025-08-04 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_remove_inscripcion_comprobante_descargado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialInscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si esta inscripción está activa o fue reemplazada')),
                ('asignaturas_snapshot', models.TextField(blank=True, help_text='JSON con las asignaturas inscritas')),
                ('grupos_snapshot', models.TextField(blank=True, help_text='JSON con los grupos asignados')),
                ('numero_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_inscripciones', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.periodo')),
            ],
            options={
                'verbose_name': 'Historial de Inscripción',
                'verbose_name_plural': 'Historial de Inscripciones',
                'ordering': ['-fecha_inscripcion'],
            },
        ),
    ]
