# Generated by Django 4.1 on 2023-07-14 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscripcion', '0004_alter_asignatura_options_alter_inscripcion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='alumnos',
            field=models.ManyToManyField(related_name='alumnos', to=settings.AUTH_USER_MODEL),
        ),
    ]
