# Generated by Django 3.2.8 on 2023-07-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_alter_inscripcion_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='inscribible',
            field=models.BooleanField(default=True),
        ),
    ]
