# Generated by Django 5.1.2 on 2024-11-12 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_alter_inscripcion_unique_together_inscripcion_grupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('numero_cuenta', 'periodo')},
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='asignatura',
            field=models.ManyToManyField(to='inscripcion.asignatura'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='asignaturas',
            field=models.ManyToManyField(related_name='asignaturas', to='inscripcion.asignatura'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='numero_cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='grupo',
        ),
    ]
