# Generated by Django 3.2.8 on 2023-07-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_asignatura_inscribible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='semestre',
            field=models.PositiveIntegerField(),
        ),
    ]
