# Generated by Django 3.2.8 on 2023-07-01 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0006_alter_asignatura_semestre'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='inscripcion',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='inscribible',
        ),
    ]
